import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });
import Providers from "./Global/Provider/Providers";
export const metadata: Metadata = {
  title: "AppWrite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <NextUIProvider> */}
        <body className={inter.className}>
          <Providers children={children}></Providers>
          <ToastContainer />
        </body>
      {/* </NextUIProvider> */}
    </html>
  );
}
